# -*- coding: utf-8 -*-
"""YOLOv8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4XLQ6c9Hcvv3jldNSRy50tBuCOVc9ZX
"""

!nvidia-smi



!pip install ultralytics

from ultralytics import YOLO

from google.colab import drive
drive.mount('/content/drive')

!yolo task = detect mode = predict model = yolov8l.pt conf = 0.25 source='https://ultralytics.com/images/bus.jpg' epochs = 50 imgsz = 640

!yolo task = detect mode = train model = yolov8l.pt data = ../content/drive/MyDrive/Dataset/data.yaml epochs = 50 imgsz = 640